### PR TITLE
e2e tests: add test asserting reconcile loop

### PR DESCRIPTION
**Pull request by maiqueb**
**What this PR does / why we need it**:
Add an e2e test that attempts to add an interface to a running pod; since originally one of the pod's network selection elements does not feature the interface name request, the dynamic networks controller cannot reconcile it.

We then update the pod's network selection elements to feature the correct interface name, which causes the reconcile loop to succeed, and the previously added interface to be added.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer** *(optional)*:

### CODE REVIEW

**Comment by maiqueb** [comment]
@kmabda after this one gets merged, and you provide / explain me how to address the nit left behind in the [level driven controller PR](https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/pull/85#issuecomment-1319876260), we should (IMO) provide a `v0.2.0` release. 

Thoughts ? 

Next, we should define a set of conditions for add / remove interfaces, and a way to set those on the pods.

**Comment by kmabda** [comment]
@maiqueb makes sense.

will get back to you on the reconcile on startup item ...

Q. Are we filtering out right now pods that uses the host network namespace ? i.e. `pod.Spec.HostNetwork == true` I thing we don't, calling multus delegated api on updates to the network annotation on these pods should not be processed since it doesn't make sense.

**Review by kmabda — APPROVED** [review]

**Comment by maiqueb** [comment]
> @maiqueb makes sense.
> 
> will get back to you on the reconcile on startup item ...
> 
> Q. Are we filtering out right now pods that uses the host network namespace ? i.e. `pod.Spec.HostNetwork == true` I thing we don't, calling multus delegated api on updates to the network annotation on these pods should not be processed since it doesn't make sense.

Right. I honestly had never thought about that previously :sweat_smile: 

IIUC, it would be adding another condition to https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/blob/5fdfb68811b7e24b3532f0a210414231855eeaa9/pkg/controller/pod.go#L246 ; return `if pod.Spec.hostNetwork` .

... logging these could also be helpful for the user.

**Comment by maiqueb** [comment]
@kmabda opened https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/issues/88 to track the host networked pods issue.

Thanks for raising it.

**Comment by kmabda** [comment]
no worries

**Pull request merged**
