### PR TITLE
Check duplicate interface name before handle DynamicInterfaceRequest

### PR DESCRIPTION
**Pull request by Longchuanzheng**
**What this PR does / why we need it**:
Check duplicate interface name before handle DynamicInterfaceRequest
If we have a pod with annotations:
```
k8s.v1.cni.cncf.io/networks: '[{"interface":"net1","name":"attachnet","namespace":"default"}]
```
Then we update it to: 
```
k8s.v1.cni.cncf.io/networks: '[{"interface":"net1","name":"attachnet","namespace":"default"},{"interface":"net1","name":"attachnet1","namespace":"default"}]'
```
due to it has duplicate interface name, it will get 400 error from multus.
This pr try to check whether we have duplicate interface name and avoid unnecessary requests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer** *(optional)*:

### CODE REVIEW

**Review by maiqueb — CHANGES_REQUESTED** [review]
Why would we validate this ? The user is providing a wrong configuration, we just pass along his wrong configuration to the layer that will handle that wrong request and piggy back the error.

**Comment by Longchuanzheng** [comment]
> Why would we validate this ? The user is providing a wrong configuration, we just pass along his wrong configuration to the layer that will handle that wrong request and piggy back the error.

Duplicate interface name appears to be a clear issue. Multus layer is likely to report an "interface already exists" error, and the processing adheres to the CNI interface specification. Therefore, optimizing to avoid unnecessary requests would be a reasonable approach. While I understand that this PR does not affect functionality.

**Comment by LionelJouin** [comment]
Another approach would be a validating webhook for pods network annotations. This would be beneficial for both Multus-CNI and the multus-dynamic-networks-controller projects. It would prevent creating this miss-configuration.

**Comment by Longchuanzheng** [comment]
> Another approach would be a validating webhook for pods network annotations. This would be beneficial for both Multus-CNI and the multus-dynamic-networks-controller projects. It would prevent creating this miss-configuration.

Validating webhook is good. Considering that multus and dynamic network controller are both Daemonset, where should we put this webhook?

**Comment by Longchuanzheng** [comment]
> Another approach would be a validating webhook for pods network annotations. This would be beneficial for both Multus-CNI and the multus-dynamic-networks-controller projects. It would prevent creating this miss-configuration.

Validating webhook is good. Considering that multus and dynamic network controller are both Daemonset, where should we put this webhook?

**Comment by maiqueb** [comment]
> > Another approach would be a validating webhook for pods network annotations. This would be beneficial for both Multus-CNI and the multus-dynamic-networks-controller projects. It would prevent creating this miss-configuration.
> 
> Validating webhook is good. Considering that multus and dynamic network controller are both Daemonset, where should we put this webhook?

Outside dynamic network controller. I am not interesting in maintaining a webhook for this.

**Pull request closed without merging**
