### PR TITLE
check hashicorp: Add hashicorp whitelist

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
Validates that no hashicorp are used beside the whitelisted ones
(because they shifted to BSL license)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer** *(optional)*:
Atm no hashicorp is used, but lets protect in case someone will add.
Based on the whitelist that CNAO uses.

### CODE REVIEW

**Review by phoracek — APPROVED** [review]
lgtm

**Comment by oshoval** [comment]
Thanks
@maiqueb can you please take a look ?

**Comment by oshoval** [comment]
Same as
https://github.com/kubevirt/macvtap-cni/pull/105#issuecomment-1807076515

**Comment by oshoval** [comment]
/close 

in case desired we can reopen

**Pull request closed without merging**
