### PR TITLE
chore: Update dependencies

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

Updated modules golang.org/x/* and github.com/emicklei/go-restful to the latest versions.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer** *(optional)*:

### CODE REVIEW

**Comment by maiqueb** [comment]
Why is this useful ?

What bumps does this unlock ? 

Why shouldn't we rely on dependabot instead ? 

@0xFelix ^

**Comment by 0xFelix** [comment]
We can stick to depenabot, but it didn't catch neither `github.com/emicklei/go-restful` nor `golang.org/x/net`. This PR updates them + all other `golang.org/x/*` dependencies.

**Comment by oshoval** [comment]
Imo we should be ok-to-test
the same effort is done on all the other repos, and is on priority right now
Thanks

**Comment by maiqueb** [comment]
Chosen to ignore the failed e2e test since our e2e tests are notoriously flaky.

**Pull request merged**
