### PR TITLE
manifests: Update Multus socket path

### PR DESCRIPTION
**Pull request by orelmisan**
**What this PR does / why we need it**:
In OKD 4.14, the Multus socket is located at the following path: `/run/multus/socket/multus.sock`

Update the example manifest accordingly.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer** *(optional)*:

### CODE REVIEW

**Review by ormergi — COMMENTED** [review]
I think you need to change the default path here https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/blob/8e060251899f99e68c312e6b97d2a585d0a0fc72/Makefile#L10C8-L11 
Then have the manifest regenerate with `make manifests`

**Comment by orelmisan** [comment]
@maiqueb Could you please share a link to the `j2` utility used by `hack/generate_manifests.sh` ?

**Comment by orelmisan** [comment]
[Change](https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/compare/fd01776ef499f8553ddec893b41144428b7c6ddc..fd079d58d437be977a8dc552ad57dc357d5d86ea): Fixed review [comment](https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/pull/155#pullrequestreview-1613121138).

**Comment by maiqueb** [comment]
> @maiqueb Could you please share a link to the `j2` utility used by `hack/generate_manifests.sh` ?

Commonly installed with pip: https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/blob/8e060251899f99e68c312e6b97d2a585d0a0fc72/.github/workflows/check.yaml#L18

**Review by maiqueb — CHANGES_REQUESTED** [review]
Thinking about the change you're making, I've checked where multus actually sets the socket. In [multus-cni](https://github.com/k8snetworkplumbingwg/multus-cni/blob/7ea924b8f156fb0633ff494c80fe7dd0d3f2bf7d/deployments/multus-daemonset-thick.yml#L120C41-L120C41).

Thus, I actually think the manifest is correct right now - it works with the current upstream. (I suspect your change will not make CI happy)

I think the issue is in openshift, where the [operator deploys this at a different path](https://github.com/openshift/cluster-network-operator/blob/master/bindata/network/multus/multus.yaml#L135).

I think the right place for these changes would be on our midstream / downstream.

**Pull request closed without merging**
